In [3]:
# When training neural networks, the most frequently used algorithm is back propagation
# In this algorithm, parameters (model weights) are adjusted according to the gradient of the loss function with respect to the given parameter.
import torch

x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5, 3, requires_grad = True)
b = torch.randn(3, requires_grad = True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [4]:
print(f"Gradient function for z: {z.grad_fn}")
print(f"Gradient function for loss: {loss.grad_fn}")

Gradient function for z: <AddBackward0 object at 0x175ba99f0>
Gradient function for loss: <BinaryCrossEntropyWithLogitsBackward0 object at 0x175c0ef20>


In [5]:
#To optimize weights in a neural network, we need to compute the derivatives of the loss function with respect to the parameters
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0011, 0.1602, 0.2318],
        [0.0011, 0.1602, 0.2318],
        [0.0011, 0.1602, 0.2318],
        [0.0011, 0.1602, 0.2318],
        [0.0011, 0.1602, 0.2318]])
tensor([0.0011, 0.1602, 0.2318])


In [6]:
z = torch.matmul(x,w) + b
print(z.requires_grad)
with torch.no_grad():
    z = torch.matmul(x,w) + b
print(z.requires_grad)

True
False


In [7]:
z = torch.matmul(x, w) + b
z_det = z.detach()
print(z_det.requires_grad)

False


In [8]:
# There are a few reasons you want to disable gradient tracking:
#    To mark some parameters in your neural network as frozen parameters (shouldn't be changed)
#    To speed up computations when you are only doing forward pass and don't care for improving your model anymore.

In [10]:
# For a vector function y = f(x) where x = <x1, x2, ...> and y = <y1, y2, ...>,
# the jacobian is a matrix is a way to represent all the partial derivatives
# Pytorch allows you to compute the Jacobian product v^T * J (the transpose of v times J)
# This is achieved by calling "backward" with v as an argument.
inp = torch.eye(4, 5, requires_grad = True)
out = (inp+1).pow(2).t()
out.backward(torch.ones_like(out), retain_graph = True)
print(f"First call\n{inp.grad}")
out.backward(torch.ones_like(out), retain_graph = True)
print(f"\nSecond call\n{inp.grad}")
inp.grad.zero_()
out.backward(torch.ones_like(out), retain_graph = True)
print(f"\nCall after zeroing gradients\n{inp.grad}")

First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
